import { ShieldCheck, TrendingUp, AlertTriangle, ListTodo, ChevronDown, ChevronUp, Info } from 'lucide-react';
import { Card, CardHeader, CardTitle, CardContent } from '../../components/ui/card';
import { Link } from 'react-router-dom';
import { useState } from 'react';

export const ICNODashboard = () => {
  const [expandedTask, setExpandedTask] = useState<number | null>(null);

  const toggleTask = (id: number) => {
    if (expandedTask === id) {
      setExpandedTask(null);
    } else {
      setExpandedTask(id);
    }
  };

  return (
    <div className="p-4 md:p-8 space-y-6">
      <header className="mb-8">
        <h1 className="text-2xl md:text-3xl font-bold text-slate-800">ICNO Overview</h1>
        <p className="text-slate-500">Daily outbreak risk & priority actions</p>
      </header>

      {/* Top Stats Row */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
        {/* Pending Validations */}
        <Card className="border-l-4 border-l-risk-pending hover:shadow-md transition-shadow">
          <CardContent className="p-6">
            <div className="flex justify-between items-start">
              <div>
                <p className="text-sm font-medium text-slate-500 mb-1">Pending Validation</p>
                <h3 className="text-3xl font-bold text-slate-800">3</h3>
              </div>
              <div className="p-3 bg-risk-pending/10 rounded-lg">
                <ShieldCheck className="text-risk-pending" size={24} />
              </div>
            </div>
            <Link to="/icno/validation" className="text-sm font-medium text-brand mt-4 inline-block hover:underline font-semibold">
              Review Inbox →
            </Link>
          </CardContent>
        </Card>

        {/* Global Compliance */}
        <Card className="border-l-4 border-l-risk-amber hover:shadow-md transition-shadow">
          <CardContent className="p-6">
            <div className="flex justify-between items-start">
              <div>
                <p className="text-sm font-medium text-slate-500 mb-1">Ward Compliance Avg</p>
                <h3 className="text-3xl font-bold text-slate-800">72%</h3>
              </div>
              <div className="p-3 bg-risk-amber/10 rounded-lg">
                <TrendingUp className="text-risk-amber" size={24} />
              </div>
            </div>
            <p className="text-sm text-slate-500 mt-4 font-medium">-4% from yesterday</p>
          </CardContent>
        </Card>

        {/* Active Outbreak Alerts */}
        <Card className="border-l-4 border-l-risk-red hover:shadow-md transition-shadow">
          <CardContent className="p-6">
            <div className="flex justify-between items-start">
              <div>
                <p className="text-sm font-medium text-slate-500 mb-1">Active High-Risk Wards</p>
                <h3 className="text-3xl font-bold text-slate-800">2</h3>
              </div>
              <div className="p-3 bg-risk-red/10 rounded-lg">
                <AlertTriangle className="text-risk-red" size={24} />
              </div>
            </div>
            <Link to="/heatmap" className="text-sm font-medium text-brand mt-4 inline-block hover:underline font-semibold">
              View Heatmap →
            </Link>
          </CardContent>
        </Card>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Priority Task List */}
        <div className="lg:col-span-2">
          <Card className="h-full border-slate-200 shadow-sm">
            <CardHeader className="border-b border-slate-100 bg-slate-50/80 p-4 md:p-6">
              <div className="flex items-center gap-2">
                <ListTodo className="text-brand" size={24} />
                <CardTitle className="text-xl text-slate-800">Priority Tasks</CardTitle>
              </div>
              <p className="text-sm text-slate-500 mt-1">Generated by Risk-Weighted Heuristic Engine</p>
            </CardHeader>
            <CardContent className="p-0">
              <div className="divide-y divide-slate-100">
                {/* Task Item 1 */}
                <div className="p-4 md:p-6 hover:bg-slate-50/50 transition-colors">
                  <div className="flex items-start justify-between">
                    <div className="flex-1 pr-4">
                      <div className="flex items-center gap-3 mb-1">
                        <span className="px-3 py-1 bg-risk-red/10 text-risk-red text-xs font-bold rounded-full border border-risk-red/20 uppercase tracking-wide">
                          Priority 1
                        </span>
                        <h4 className="font-bold text-slate-800 text-lg">Investigate Dengue Spike</h4>
                      </div>
                      <p className="text-slate-600 mt-2 font-medium">Ward 04 (General Medicine)</p>
                      <p className="text-sm text-slate-500 mt-1">Z-Score anomaly detected in recent 48h. Routine hygiene scored low.</p>
                      
                      <button 
                        onClick={() => toggleTask(1)}
                        className="mt-4 text-sm font-medium text-brand flex items-center gap-1 hover:underline"
                      >
                        {expandedTask === 1 ? <ChevronUp size={16}/> : <ChevronDown size={16}/>}
                        View Heuristic Breakdown
                      </button>

                      {expandedTask === 1 && (
                        <div className="mt-4 p-4 bg-slate-100 rounded-lg animate-in fade-in slide-in-from-top-2">
                           <h5 className="text-xs font-bold text-slate-500 uppercase tracking-wider mb-3">Risk Calculation: P = (w1·C) + (w2·V) + (w3·L)</h5>
                           <div className="grid grid-cols-3 gap-4">
                             <div className="bg-white p-3 rounded shadow-sm border border-slate-200">
                               <p className="text-xs text-slate-500 mb-1 flex items-center gap-1"><Info size={12}/> Clinical (C)</p>
                               <p className="text-lg font-bold text-risk-red">0.85</p>
                               <p className="text-xs text-slate-400 mt-1">High pathogen frequency</p>
                             </div>
                             <div className="bg-white p-3 rounded shadow-sm border border-slate-200">
                               <p className="text-xs text-slate-500 mb-1 flex items-center gap-1"><Info size={12}/> Vulnerability (V)</p>
                               <p className="text-lg font-bold text-risk-amber">0.60</p>
                               <p className="text-xs text-slate-400 mt-1">Moderate patient risk</p>
                             </div>
                             <div className="bg-white p-3 rounded shadow-sm border border-slate-200">
                               <p className="text-xs text-slate-500 mb-1 flex items-center gap-1"><Info size={12}/> Logistics (L)</p>
                               <p className="text-lg font-bold text-risk-red">0.90</p>
                               <p className="text-xs text-slate-400 mt-1">Critical resource shortage</p>
                             </div>
                           </div>
                        </div>
                      )}
                    </div>
                  </div>
                </div>

                {/* Task Item 2 */}
                <div className="p-4 md:p-6 hover:bg-slate-50/50 transition-colors">
                  <div className="flex items-start justify-between">
                    <div className="flex-1 pr-4">
                      <div className="flex items-center gap-3 mb-1">
                        <span className="px-3 py-1 bg-risk-amber/10 text-risk-amber text-xs font-bold rounded-full border border-risk-amber/20 uppercase tracking-wide">
                          Priority 2
                        </span>
                        <h4 className="font-bold text-slate-800 text-lg">Audit Review Required</h4>
                      </div>
                      <p className="text-slate-600 mt-2 font-medium">Maternity Ward</p>
                      <p className="text-sm text-slate-500 mt-1">Hand hygiene compliance dropped below 60% threshold for two consecutive days.</p>
                      
                      <button 
                        onClick={() => toggleTask(2)}
                        className="mt-4 text-sm font-medium text-brand flex items-center gap-1 hover:underline"
                      >
                        {expandedTask === 2 ? <ChevronUp size={16}/> : <ChevronDown size={16}/>}
                        View Heuristic Breakdown
                      </button>

                      {expandedTask === 2 && (
                        <div className="mt-4 p-4 bg-slate-100 rounded-lg animate-in fade-in slide-in-from-top-2">
                           <h5 className="text-xs font-bold text-slate-500 uppercase tracking-wider mb-3">Risk Calculation: P = (w1·C) + (w2·V) + (w3·L)</h5>
                           <div className="grid grid-cols-3 gap-4">
                             <div className="bg-white p-3 rounded shadow-sm border border-slate-200">
                               <p className="text-xs text-slate-500 mb-1 flex items-center gap-1"><Info size={12}/> Clinical (C)</p>
                               <p className="text-lg font-bold text-risk-green">0.20</p>
                             </div>
                             <div className="bg-white p-3 rounded shadow-sm border border-slate-200">
                               <p className="text-xs text-slate-500 mb-1 flex items-center gap-1"><Info size={12}/> Vulnerability (V)</p>
                               <p className="text-lg font-bold text-risk-red">0.85</p>
                             </div>
                             <div className="bg-white p-3 rounded shadow-sm border border-slate-200">
                               <p className="text-xs text-slate-500 mb-1 flex items-center gap-1"><Info size={12}/> Logistics (L)</p>
                               <p className="text-lg font-bold text-risk-amber">0.50</p>
                             </div>
                           </div>
                        </div>
                      )}
                    </div>
                  </div>
                </div>
              </div>
            </CardContent>
          </Card>
        </div>

        {/* AI Root Cause Associations */}
        <div className="lg:col-span-1">
          <Card className="h-full border-slate-200 shadow-sm">
            <CardHeader className="border-b border-slate-100 bg-slate-50/80 p-4 md:p-6">
              <CardTitle className="text-xl text-slate-800 flex items-center gap-2">
                 Root Cause Insights
              </CardTitle>
              <p className="text-sm text-slate-500 mt-1">Apriori association engine</p>
            </CardHeader>
            <CardContent className="p-4 md:p-6 space-y-4">
              <div className="bg-risk-amber/10 p-5 rounded-xl border border-risk-amber/30 relative overflow-hidden">
                <div className="absolute top-0 left-0 w-1 h-full bg-risk-amber"></div>
                <div className="flex justify-between items-start mb-2">
                  <span className="text-xs font-bold text-risk-amber uppercase tracking-wider">Strong Link</span>
                  <span className="text-xs font-bold bg-white text-slate-600 px-2 py-1 rounded shadow-sm">85% Conf</span>
                </div>
                <p className="text-sm text-slate-800 leading-relaxed font-medium">
                  Poor <span className="font-bold underline decoration-risk-amber/50 decoration-2">waste segregation</span> in Ward 04 correlates strongly with recent <span className="font-bold underline decoration-risk-amber/50 decoration-2">Dengue cases</span>.
                </p>
              </div>

              <div className="bg-slate-50 p-5 rounded-xl border border-slate-200 relative overflow-hidden">
                <div className="absolute top-0 left-0 w-1 h-full bg-slate-400"></div>
                <div className="flex justify-between items-start mb-2">
                  <span className="text-xs font-bold text-slate-500 uppercase tracking-wider">Moderate Link</span>
                  <span className="text-xs font-bold bg-white text-slate-600 px-2 py-1 rounded shadow-sm">62% Conf</span>
                </div>
                <p className="text-sm text-slate-800 leading-relaxed font-medium">
                  Missing <span className="font-bold underline decoration-slate-300 decoration-2">PPE protocol</span> in ICU correlates with <span className="font-bold underline decoration-slate-300 decoration-2">anomalous pathogen spikes</span>.
                </p>
              </div>
            </CardContent>
          </Card>
        </div>
      </div>
    </div>
  );
};
