"""
InfecSure — Audits Router
==========================
POST /audits/                → submit a new ward audit (ICNO only)
GET  /audits/                → list all audits
GET  /audits/{audit_id}      → get specific audit
GET  /audits/priority-list   → AI-generated task priority list (ICNO only)
"""

from __future__ import annotations

from fastapi import APIRouter, Depends, HTTPException, status

from app.dependencies import get_current_user, require_role
from app.models.audit import AuditCreate, WardAudit
from app.models.auth import TokenData
from app.models.user import UserRole
from app.services import firebase_service as fs
from app.services import ml_service

router = APIRouter(prefix="/audits", tags=["Ward Audits"])

_ALL_AUTH = Depends(get_current_user)
_ICNO_ONLY = Depends(require_role(UserRole.ICNO))


@router.post("/", status_code=status.HTTP_201_CREATED, summary="Submit ward audit (ICNO only)")
async def create_audit(body: AuditCreate, current_user: TokenData = Depends(require_role(UserRole.ICNO))):
    """
    Submit a digital ward audit. Automatically calculates overall compliance score
    and updates the ward record. Triggers Re-assessment of ward risk.
    """
    ward = fs.get_ward(body.ward_id)
    if not ward:
        raise HTTPException(status_code=404, detail="Ward not found.")

    # Compute overall compliance (average of all four scores)
    scores = [
        body.hand_hygiene_score,
        body.ppe_score,
        body.waste_segregation_score,
        body.environmental_score,
    ]
    overall = sum(scores) / len(scores)

    # Get user display name
    user_doc = fs.get_user_by_uid(current_user.uid)
    user_name = user_doc.get("full_name", current_user.email) if user_doc else current_user.email

    data = body.model_dump()
    # Serialize nested Pydantic objects
    data["hand_hygiene_items"] = [i.model_dump() for i in body.hand_hygiene_items]
    data["ppe_items"] = [i.model_dump() for i in body.ppe_items]
    data["waste_segregation_items"] = [i.model_dump() for i in body.waste_segregation_items]
    data["environmental_items"] = [i.model_dump() for i in body.environmental_items]
    data["overall_compliance_score"] = round(overall, 2)
    data["conducted_by_uid"] = current_user.uid
    data["conducted_by_name"] = user_name

    audit_id = fs.create_audit(data)

    # Update ward compliance & last audit timestamp
    from datetime import datetime, timezone
    fs.update_document("wards", body.ward_id, {
        "compliance_score": round(overall, 2),
        "last_audit_at": datetime.now(timezone.utc),
    })

    # Trigger compliance failure alert if overall < 70%
    if overall < 70.0:
        fs.create_alert({
            "alert_type": "compliance_failure",
            "ward_id": body.ward_id,
            "title": f"Compliance Failure — {ward.get('name', body.ward_id)}",
            "description": (
                f"Ward compliance dropped to {overall:.1f}% (below 70% threshold). "
                f"Conducted by {user_name}."
            ),
            "severity": "high" if overall < 50 else "medium",
            "source_data": {"overall_compliance_score": overall},
            "target_roles": ["icno", "sister"],
        })

    return {
        "audit_id": audit_id,
        "overall_compliance_score": round(overall, 2),
        "message": "Audit submitted and ward risk updated.",
    }


@router.get("/", summary="List all audits")
async def list_audits(current_user: TokenData = _ALL_AUTH):
    """Returns all ward audit records. Accessible to all authenticated roles."""
    return fs.list_all_audits()


@router.get("/priority-list", summary="AI Task Priority List (ICNO only)")
async def get_priority_list(_: TokenData = _ICNO_ONLY):
    """
    Returns the ICNO's prioritized daily task list generated by the
    Risk-Weighted Heuristic Engine:
    P = (w1 * C) + (w2 * V) + (w3 * L)
    Sorted by priority score (highest first).
    """
    return ml_service.calculate_task_priority()


@router.get("/{audit_id}", summary="Get specific audit")
async def get_audit(audit_id: str, _: TokenData = _ALL_AUTH):
    audit = fs.get_audit(audit_id)
    if not audit:
        raise HTTPException(status_code=404, detail="Audit not found.")
    return audit
