"""
InfecSure - Ward Audits Router
"""

from __future__ import annotations

from fastapi import APIRouter, Depends, HTTPException, status

from app.dependencies import get_current_user, require_role
from app.models.audit import AuditCreate, AuditSyncRequest
from app.models.auth import TokenData
from app.models.user import UserRole
from app.services import audit_service, domain_service, fallback_data, firebase_service as fs, ml_service

router = APIRouter(prefix="/audits", tags=["Ward Audits"])

_ALL_AUTH = Depends(get_current_user)
_ICNO_ONLY = Depends(require_role(UserRole.ICNO))


@router.post("/", status_code=status.HTTP_201_CREATED, summary="Submit ward audit (ICNO only)")
async def create_audit(
    body: AuditCreate,
    current_user: TokenData = Depends(require_role(UserRole.ICNO)),
):
    """
    Submit a ward audit, calculate compliance score, update ward risk, and
    create compliance alerts when needed.
    """
    try:
        return domain_service.create_audit(
            body,
            conducted_by_uid=current_user.uid,
            conducted_by_email=current_user.email,
        )
    except ValueError as exc:
        message = str(exc)
        status_code = 404 if "not found" in message.lower() else 400
        raise HTTPException(status_code=status_code, detail=message)
    except Exception as exc:
        if fallback_data.is_quota_error(exc):
            raise HTTPException(
                status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
                detail="Firestore quota exceeded. Save this audit offline and sync it when the database is available.",
            )
        raise


@router.get("/", summary="List all audits")
async def list_audits(limit: int = 50, current_user: TokenData = _ALL_AUTH):
    """Returns all ward audit records. Accessible to all authenticated roles."""
    return fs.list_all_audits(limit=min(max(limit, 1), 100))


@router.post("/sync", status_code=status.HTTP_201_CREATED, summary="Sync offline PWA audit records")
async def sync_audits(
    body: AuditSyncRequest,
    current_user: TokenData = _ICNO_ONLY,
):
    """
    Receive batched audit data captured offline in IndexedDB and commit each
    valid record through the same audit workflow as manual submissions.
    """
    results = []
    for index, item in enumerate(body.records):
        try:
            audit, metrics = audit_service.build_audit_from_sync(item)
            created = domain_service.create_audit(
                audit,
                conducted_by_uid=current_user.uid,
                conducted_by_email=current_user.email,
                source="offline_sync",
                extra_data=metrics,
            )
            results.append({
                "index": index,
                "offline_record_id": item.offline_record_id,
                "status": "created",
                **created,
                **metrics,
            })
        except Exception as exc:
            results.append({
                "index": index,
                "offline_record_id": item.offline_record_id,
                "status": "failed",
                "error": str(exc),
            })

    return {
        "received": len(body.records),
        "created": sum(1 for r in results if r["status"] == "created"),
        "failed": sum(1 for r in results if r["status"] == "failed"),
        "results": results,
    }


@router.get("/priority-list", summary="AI Task Priority List (ICNO only)")
async def get_priority_list(_: TokenData = _ICNO_ONLY):
    """
    Returns the ICNO's prioritized daily task list generated by the
    Risk-Weighted Heuristic Engine.
    """
    try:
        return ml_service.calculate_task_priority()
    except Exception as exc:
        if fallback_data.is_quota_error(exc):
            return fallback_data.priority_list()
        raise


@router.get("/{audit_id}", summary="Get specific audit")
async def get_audit(audit_id: str, _: TokenData = _ALL_AUTH):
    audit = fs.get_audit(audit_id)
    if not audit:
        raise HTTPException(status_code=404, detail="Audit not found.")
    return audit
